spring:
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    properties:
      hibernate:
        default_schema: heroku_c250dadf7effe4c

  datasource:
    url: jdbc:mysql://us-cdbr-iron-east-01.cleardb.net/heroku_c250dadf7effe4c
    username: b1db4aa9b13e19
    password: b0c90b8a

  #https://developers.facebook.com/apps/ for facebook
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 528552864734150
            client-secret: ae5c907268c4c411214b3a8b3487e14a
            scope:
              - email