spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driverClassName: org.h2.Driver
    initialization-mode: always
    url: jdbc:h2:mem:testdb
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  #https://developers.facebook.com/apps/ for facebook
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 528552864734150
            client-secret: ae5c907268c4c411214b3a8b3487e14a
            scope:
              - email
